# Therotical questions

1. Explain the purpose and advantages of Numpy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

Ans:Purpose of numpy:

1.Efficient data manipulation and storage: NumPy supports arrays, particularly multi-dimensional arrays, which are more effective for numerical data than Python's built-in lists.
   
2.Mathematical operations: It provides a large set of performance-optimized mathematical functions and operations (such as matrix operations, linear algebra, statistical functions, etc.).

3.Foundation for other libraries: NumPy provides the groundwork for numerous other scientific libraries, including SciPy, Pandas, and machine learning libraries like PyTorch and TensorFlow.

Advantages of numpy:

1.Performance: Because NumPy is implemented in C, which brings it closer to hardware level, operations on NumPy arrays are substantially faster than on conventional Python lists.
   
2.Memory efficiency: Because NumPy arrays store data in a single, continuous block of memory, they require less memory than Python lists.

3.Vectorization: NumPy enables operations to be applied element-wise on arrays without the need for creating loops, improving readability and reducing error rates.

4.Broadcasting: NumPy automatically manages actions (such adding a scalar to an array) on arrays of various forms in a way that prevents mistakes or human changes.




2. Compare and contrast np.mean() and np.average() functions in Numpy. When would you use one over the other?

Ans:1. np.mean():

1.Goal: Determines the array's arithmetic mean (average) along a given axis, or the array as a whole in the absence of an axis.

2.Weights: All factors are treated equally; weighted averages are not supported.

3.Usage: If you only require the basic arithmetic mean, use np.mean().


2.The np.average function

1.Purpose: Functions similarly to np.mean(), but if weights are supplied, it can also compute a weighted average.

2.Weights: You can give each element in the array a different weight based on its importance because it supports weighted averages.

3.Usage: If you require a weighted average or think you might need to add weights later, use np.average().

When to use it: (i) For faster and easier simple, unweighted averages, use np.mean().

(ii)If you need to compute a weighted average, use np.average(). If no weights are specified, it behaves like np.mean().



3. Describe the methods for reversing a Numpy array along different axes. Provide examples for ID and 2D arrays.

Ans:NumPy arrays can be reversed along different axes using slicing or dedicated operations. To reverse 1D and 2D arrays, follow these steps:

1.Reversing a 1D array: Slicing with a step of -1 can be used to reverse a 1D array.

## Let's take example to understand

In [30]:
# Reversing 1D array

import numpy as np
arr1=np.array([1,2,3,4])

reversedarr1 = arr1[::-1]

print(reversedarr1)

[4 3 2 1]


2.Reversing a 2D Array: By designating the axis during slicing, 2D arrays can be reversed along several axes (rows or columns).


In [31]:
import numpy as np

# 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse along axis 0 (rows)
reversed_rows = arr_2d[::-1, :]

print(reversed_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Example 3: Reverse all columns and rows.

It is possible to slice both axes in order to reverse rows and columns:


In [32]:
# Reverse both rows and columns
reversed_both = arr_2d[::-1, ::-1]

print(reversed_both)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


4. How can you determine the data type of elements in a Numpy array? Discuss the importance of data types in memory management and performance.

Ans:The.dtype attribute in a NumPy array can be used to determine the data type of its elements.


In [33]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype) 

arr_float = np.array([1.0, 2.0, 3.0])
print(arr_float.dtype)  


int32
float64


Memory: The Significance of Data Types

1.Memory needs vary depending on the type of data. Memory is used differently for larger data types (like int64) and smaller data types (like int8).
   
2.Memory can be saved by selecting the appropriate data type. For instance, when working with simple whole integers, avoid using float64.

Speed: 

1.Because smaller data types use less memory, operations on them are typically faster.

2.Because they require more space, larger data types may cause a little speed decrease.

Accuracy: 

Results from some data types are more exact. Float64, for instance, has more accuracy than Float32.

5. Define ndarrays in Numpy and explain their key features. How do they differ from standard Python lists?

Ans:N-dimensional arrays, or ndarrays, are the fundamental data structures of NumPy that are used to effectively store and handle massive data sets. It has the capacity to store data in many dimensions (1D, 2D, 3D, etc.) of the same type.


Key characteristics of ndarrays:

1.Homogeneous Data: An ndarray can only include elements of the same type, such as all integers or all floats. Faster processing and efficient memory use are made possible by this.

2.Fixed Size: Unlike Python lists, which allow for dynamic size changes, an ndarray's size (the total number of elements) is fixed once it is constructed.

3.N-dimensional: An ndarray (such as a 1D, 2D, or 3D array) can have any number of dimensions. For jobs like dealing with matrices or 3D data, this makes it appropriate.

How do they differ from standard Python lists?

A NumPy ndarray is not the same as a Python list in a few important aspects. Firstly, unlike Python lists, which can contain elements of various kinds, ndarrays require all of its elements to be of the same data type (for example, all integers or all floats). This improves the memory efficiency of ndarrays. Unlike Python lists, which are dispersed throughout memory, arrays are kept in continuous blocks of memory, facilitating quicker data access and manipulation. The fact that ndarrays can have various dimensions (1D, 2D, 3D, etc.) is another significant distinction. 

Python lists, on the other hand, can be nestled to imitate several dimensions, but they are ultimately one-dimensional. Additionally, unlike Python lists, which can grow or shrink dynamically, NumPy arrays have a fixed size after formation, meaning that their length cannot be altered. Last but not least, ndarray operations are far faster than Python lists since NumPy performs vectorized operations on full arrays at once, whereas Python lists typically need loops to process each element separately. Ndarrays are more suited for scientific computing and big datasets because of these distinctions.

6. Analyze the performance benefits of Numpy arrays over Python lists for large-scale numerical operations.

Ans:Performance Benefits of NumPy Arrays over Python Lists:

(i)Memory Efficiency:

1.Compared to Python lists, NumPy arrays (ndarrays) have a higher memory efficiency. Memory overhead is decreased by arrays, which employ a fixed type for every element and store data in contiguous memory blocks.

2.Due to their ability to carry references to objects and a variety of data types, Python lists are more versatile but less memory-efficient.

(ii)Quicker Performance:

1.Vectorized operations, which let you operate on arrays element-by-element without the need for loops, are advantageous to NumPy arrays. Compared to Python lists, where processing elements one by one usually requires explicit loops, this is substantially faster.

2.NumPy is internally implemented in C and skips over Python's slower interpretation stage by performing operations at a lower level.

(iii)Broadcasting: By using broadcasting, which involves "stretched" smaller arrays to fit the shape of larger arrays without explicitly duplicating data, NumPy can perform operations on arrays with varying shapes. Large-scale activities can operate faster as a result of avoiding manual scaling.

(iv)Optimized Mathematical Functions: NumPy includes built-in functions for multiple operations, including addition, subtraction, linear algebra, and trigonometry. Compared to expressing the same logic with Python lists, these functions are far more efficient and operate more quickly.

(v)Multi-dimensional Support: NumPy effectively manages multi-dimensional arrays, such as matrices, whereas Python lists necessitate laborious, costly loops and manual nesting in order to operate with comparable structures. In scientific computing, where high-dimensional data is frequently encountered, this is especially helpful.



7.Compare vstack() and hstack() functions in Numpy. Provide examples demonstrating their usage and output.

Ans:1.vstack(): This function operates row-wise and stacks arrays vertically (on top of one another). There must be an equal number of columns.

2.hstack(): This function operates column-wise and stacks arrays horizontally (side by side). There must be an equal number of rows.

When combining arrays vertically or horizontally to create larger arrays or matrices, these functions come in handy.

## Let's take example to understand

In [34]:
## vsatck

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertically stack them
result_vstack = np.vstack((arr1, arr2))

print(result_vstack)


[[1 2 3]
 [4 5 6]]


In [35]:
## hstack

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Horizontally stack them
result_hstack = np.hstack((arr1, arr2))

print(result_hstack)


[1 2 3 4 5 6]


In [36]:
## for 2d array

arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4], [5], [6]])

result_hstack = np.hstack((arr1, arr2))
print(result_hstack)


[[1 4]
 [2 5]
 [3 6]]


In [37]:
##2 d array

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

result_vstack = np.vstack((arr1, arr2))
print(result_vstack)


[[1 2 3]
 [4 5 6]]


8.Explain the differences between flipir() and flipud() methods in NumPy, including their effects on various array dimensions.

Ans:The flipud() and fliplr() functions in NumPy are used to flip arrays along different axes. This is how they vary:

1.np.flipud() (Flip Up-Down): 
i)purpose:This function flips an array upside down, or in other words, it reverses the row order.

ii)Effect: The columns of an array remain unaltered; it simply modifies the array's first axis, or rows.

iii)Use case: When a 2D array's rows need to be inverted vertically.

## Let's take example to understand

In [38]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip upside down
result_flipud = np.flipud(arr)

print(result_flipud)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Ans:2. Left-to-right flip (np.fliplr()):
i)purpose:The goal is to flip an array from left to right, or to reverse the column order.

ii)Effect: The rows of an array remain unaltered; it simply modifies the array's second axis, or the columns.

iii)Use case: When a 2D array's column horizontal order needs to be reversed.

## Let's take example to understand

In [39]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Flip left to right
result_fliplr = np.fliplr(arr)

print(result_fliplr)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


Effects on Array Dimensions: flipud():

1.It flips the array for a 1D array, which is equivalent to reversing the element order.

2.It flips the rows (vertical axis) of a 2D array while leaving the columns unaltered.

3.It impacts the first axis for greater dimensions (e.g., flipping a 3D array along the vertical axis).


fliplr():

1.Since there is no "left" or "right" in a 1D array, it does not apply.

2.It flips the columns (horizontal axis) of a 2D array, leaving the rows unaltered.

3.It impacts the second axis in greater dimensions (e.g., flipping a 3D array along the horizontal axis).


9. Discuss the functionality of the array _split ) method in Numpy. How does it handle uneven splits?

Ans:A number of sub-arrays can be created from an array using the numpy.array_split() function. Compared to numpy.split(), it offers greater flexibility, especially in situations where the array cannot be divided equally into the desired number of smaller arrays.

Functionality of numpy.array_split():

.basic syntax
numpy.array_split(ary, indices_or_sections, axis=0)

i)ary: The array of input that has to be split.

ii)sections_or_indices: This can be a list of indices where the array should be split, or it can be an integer (the number of equal sections to split into).

iii)axis: The array's axis of division (default is 0).

Important characteristics:
1. Flexible Splitting: array_split() permits unequal splits without producing an error, in contrast to numpy.split(), which demands that the array be equally divisible by the number of splits.
2. provides a List: In the event that the original array cannot be divided equally, it provides a list of sub-arrays, each of which may have a different shape.

Handling Uneven Splits: 
array_split() attempts to divide the elements as evenly as it can when the array cannot be split evenly. If any elements remain, they are divided one by one into each sub-array, beginning with the first one.
   
## let's take example to understand

In [40]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
result = np.array_split(arr, 3)

print(result)


[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [41]:
## [array([1, 2, 3]), array([4, 5]), array([6, 7])] # The array [1, 2, 3, 4, 5, 6, 7] is divided into three sub-arrays in this example. Seven elements can't be divided into three equal pieces, therefore the first sub-array has three elements, while the other two have two each.


10. Explain the concepts of vectorization and broadcasting in Numpy. How do they contribute to efficient array operations?

Ans:NumPy vectorization:
Applying operations to whole arrays or subsets of arrays without explicitly utilizing loops is known as vectorization. NumPy lets you operate on entire arrays at once rather than iterating through each element one at a time. This is made feasible by NumPy's performance-optimized C implementation, which makes array operations significantly faster than with conventional Python loops.

Advantages of Vectorization

1. Speed: Due to the use of low-level optimizations and the avoidance of Python's loop structures, vectorized operations are substantially faster than looping through elements.
2. Simplicity: Because complex actions can be carried out in a single line without the requirement for explicit iteration, the code becomes cleaner and easier to comprehend.
3. Less Error-Prone: Less complexity and code means less opportunities for errors to occur.


Broadcasting in NumPy:
NumPy's sophisticated broadcasting system enables it to conduct actions on arrays of varying shapes so that they appear to be of the same shape. NumPy automatically resizes the arrays to compatible sizes when executing arithmetic operations.

Guidelines for Broadcasting:

1. The smaller-dimensional array is padded with ones on the left side until both arrays have the same number of dimensions if the arrays have different dimensions.
2. NumPy compares the dimensions if their sizes differ:
3. Broadcasting is possible if both of them are equal or if one of them is 1.
4. An error is raised if they are not compatible, meaning they are not equal and neither is 1.


Contributions to Efficient Array Operations:

1. Reduced Computational Load: Loops, which are computationally costly in Python, are avoided when using vectorization and broadcasting. NumPy significantly increases speed by utilizing optimized C methods.
2. Improved Readability and Maintainability: When code makes use of broadcasting and vectorization, it is frequently easier to understand and update than when the same code makes use of explicit loops. As a result, it is easier to grasp and less likely to include errors.
3. Flexibility: Broadcasting enables you to work with arrays of various forms, which is especially helpful in data analysis and scientific computing because datasets may differ in size.
4. Memory Efficiency: Vectorization and broadcasting aid in memory optimization by preventing needless data copies (as with looping), which makes operations on big datasets more practical.


# Practical Questions

1. Create a 3X3 Numpy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [53]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

print("Original Array:")
print(array)

# Interchange rows and columns (transpose)
transposed_array = np.transpose(array)

print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[45  8 32]
 [33 29  4]
 [53  5 78]]

Transposed Array:
[[45 33 53]
 [ 8 29  5]
 [32  4 78]]


2. Generate a ID NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [54]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # This will create an array with values from 0 to 9

print("Original 1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

print("\nReshaped into 5x2 Array:")
print(array_5x2)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


4. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [55]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("\nArray with Zero Border (6x6):")
print(array_with_border)


Original 4x4 Array:
[[0.54928095 0.54281665 0.26038955 0.7581071 ]
 [0.53643719 0.70634461 0.69505394 0.27462764]
 [0.17253807 0.21383483 0.25842828 0.039402  ]
 [0.92742962 0.773882   0.56012587 0.29112871]]

Array with Zero Border (6x6):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.54928095 0.54281665 0.26038955 0.7581071  0.        ]
 [0.         0.53643719 0.70634461 0.69505394 0.27462764 0.        ]
 [0.         0.17253807 0.21383483 0.25842828 0.039402   0.        ]
 [0.         0.92742962 0.773882   0.56012587 0.29112871 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


5. Create a Numpy array of strings ['python, 'numpy, 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [56]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

print("Original Array:")
print(array)

# Apply uppercase transformation
upper_case = np.char.upper(array)
print("\nUppercase:")
print(upper_case)

# Apply lowercase transformation
lower_case = np.char.lower(array)
print("\nLowercase:")
print(lower_case)

# Apply title case transformation (capitalize the first letter of each word)
title_case = np.char.title(array)
print("\nTitle Case:")
print(title_case)

# Apply capitalize transformation (capitalize only the first letter of each string)
capitalize_case = np.char.capitalize(array)
print("\nCapitalize (first letter):")
print(capitalize_case)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalize (first letter):
['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [57]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

print("Original Array:")
print(words)

# Insert a space between each character in every word
spaced_words = np.char.join(' ', words)

print("\nWords with spaces between characters:")
print(spaced_words)


Original Array:
['python' 'numpy' 'pandas']

Words with spaces between characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D Numpy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [58]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

# Element-wise addition
addition = array1 + array2
print("\nElement-wise Addition:")
print(addition)

# Element-wise subtraction
subtraction = array1 - array2
print("\nElement-wise Subtraction:")
print(subtraction)

# Element-wise multiplication
multiplication = array1 * array2
print("\nElement-wise Multiplication:")
print(multiplication)

# Element-wise division
division = array1 / array2
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8. Use Numpy to create a 5x5 identity matrix, then extract its diagonal elements.

In [59]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a Numpy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [60]:
import numpy as np

# Function to check if a number is prime
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

print("Array of random integers:")
print(random_integers)

# Find all prime numbers in the array
prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("\nPrime numbers in the array:")
print(prime_numbers)


Array of random integers:
[926 628 856 433 310 818 773 652 664 218 653 426  88 680 155 858  48 705
 826 466 699 333 959 492  61  10 113  40 706 366 492   3 143  69 231 612
 194 125 392 741 173 976 788 605 514 181 635 130 230 303  32 809 749 232
 826   6 284 908 734 325 544 453 976 724 216 632 280 492 512 330 641 444
 540 867 184 741 924  46 142 643  67 793 827 954  63 633 908 280 409 501
 594 590 651 759  31  98  60 121 513  38]

Prime numbers in the array:
[433 773 653  61 113   3 173 181 809 641 643  67 827 409  31]


10. Create a Numpy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [61]:
import numpy as np

# Create a NumPy array representing daily temperatures for 30 days (1 month)
daily_temperatures = np.random.randint(15, 35, size=30)  # Random temperatures between 15 and 35

print("Daily Temperatures (30 days):")
print(daily_temperatures)

# Reshape the array to 4 weeks (4 rows, 7 days per week)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)  # Take the first 28 days for complete weeks

# Calculate weekly averages
weekly_averages = weekly_temperatures.mean(axis=1)

print("\nWeekly Averages:")
print(weekly_averages)


Daily Temperatures (30 days):
[31 27 21 30 20 27 23 26 34 26 22 27 28 27 33 24 25 16 33 15 15 27 32 31
 31 23 32 33 26 29]

Weekly Averages:
[25.57142857 27.14285714 23.         29.85714286]
